.PHONY: clean All

All:
	@echo "----------Building project:[ Verification - Win32 Debug ]----------"
	@"$(MAKE)" -f  "Verification.mk"
clean:
	@echo "----------Cleaning project:[ Verification - Win32 Debug ]----------"
	@"$(MAKE)" -f  "Verification.mk" clean
